marquee_enabled:
  type: bool
  default: true
marquee_speed:
  default: 60
  min: 1
  max: 600
  description:
    en: text speed, between 1 and 1000, lower is faster
marquee_list:
  type: list
  default: item1|item2
