marquee_enabled:
  type: bool
  default: true
marquee_speed:
  default: 60
  min: 1
  max: 1000
  description:
    en: text speed, between 1 and 1000, lower is faster
marquee_list:
  type: list
  default: item1|item2
marquee_only_visible_to_logged_in_users:
  type: bool
  default: true
marquee_location_below_header_bar:
  type: bool
  default: false
  description:
    en: tick this if you want to show marquee <strong>below</strong> header bar instead of <strong>above</strong> header bar
